In [1]:
import numpy as np

In [1]:
!pip install pyvis

     -------------------------------------- 748.9/748.9 kB 3.9 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
     ---------------------------------------- 40.5/40.5 kB 2.0 MB/s eta 0:00:00
  Created wheel for pyvis: filename=pyvis-0.3.1-py3-none-any.whl size=755834 sha256=ff6a4bfb91cbad50004cdec75574c8fbe061d5bda615ef22d22f2429921d3507
  Stored in directory: c:\users\okadalab-pc-mouse1\appdata\local\pip\cache\wheels\58\42\e1\22469ed9fbeed51b384ae2dd29e2a16d988a768eb05c990c51
Successfully built pyvis



[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
from pyvis.network import Network

<frozen importlib._bootstrap>:219: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject


In [4]:
cof=np.load("sensitivity_coefficients/parameter/integral.npy")

In [4]:
cof.shape

(20, 33, 14, 2)

In [5]:
hcof=cof[:,:,6,0]

In [6]:
pcof=cof[:,:,6,1]

In [7]:
hcof.shape

(20, 33)

In [7]:
hcof_mean=np.mean(hcof, axis=0)

In [8]:
pcof_mean=np.mean(pcof, axis=0)

In [10]:
hcof_mean

array([-0.07399196,  0.07286357,  0.00541262,  0.0313633 , -0.61868749,
        0.64366461, -0.0693638 ,  0.08163691,  0.12908447, -0.10630969,
       -0.00156399,  0.05099043, -0.0319998 , -0.04506202, -0.00132568,
       -0.00189915,  0.02753447,  0.00153457,  0.08325021,  0.00362641,
       -0.00103057,  0.10481268, -0.08188257, -0.17300552,  0.11343262,
        0.16406425, -0.11673854, -0.21171228, -0.26140756, -0.056671  ,
        0.45429907, -0.15017526, -0.07997475])

In [11]:
pcof_mean

array([-0.47909442,  0.47294967,  0.01511355,  0.07998913, -1.1680912 ,
        0.70770132, -0.3844832 ,  0.1492603 ,  0.20969782, -0.13904519,
       -0.01173637,  0.12735586, -0.04885788, -0.07648703, -0.00312628,
       -0.0039963 ,  0.03314228,  0.00301038,  0.11701093,  0.0053148 ,
       -0.00192508,  0.18596243, -0.10724153, -0.347278  ,  0.18266686,
        0.32660184, -0.16239549, -0.34528548, -0.34015795, -0.14316328,
        0.56726578, -0.1874752 , -0.04215821])

In [12]:
np.log(pcof_mean)

<ipython-input-12-b1365a001da5>:1: RuntimeWarning: invalid value encountered in log
  np.log(pcof_mean)


array([        nan, -0.7487663 , -4.19216391, -2.52586456,         nan,
       -0.34573314,         nan, -1.90206354, -1.56208776,         nan,
               nan, -2.06077008,         nan,         nan,         nan,
               nan, -3.40694546, -5.80569047, -2.14548795, -5.23726006,
               nan, -1.68221062,         nan,         nan, -1.70009122,
       -1.11901347,         nan,         nan,         nan,         nan,
       -0.56692734,         nan,         nan])

In [9]:
ratiocof=pcof_mean/hcof_mean

In [11]:
#ratiocof[15:21]=0

In [10]:
ratiocof

array([6.47495273, 6.49089351, 2.7922795 , 2.55040573, 1.8880149 ,
       1.09948769, 5.54299488, 1.82834328, 1.62450071, 1.30792581,
       7.50410006, 2.49764252, 1.52681823, 1.69737216, 2.35825183,
       2.1042565 , 1.20366507, 1.96171175, 1.40553316, 1.46557987,
       1.86796941, 1.77423599, 1.30969916, 2.00732318, 1.6103557 ,
       1.99069473, 1.39110437, 1.6309185 , 1.30125523, 2.5262177 ,
       1.24866155, 1.2483761 , 0.52714403])

In [84]:
max(ratiocof)

6.686634917037146

In [12]:
colorlis=[]
widlis=[]
rlis=[]

In [13]:
for i in range(len(ratiocof)):
    if pcof_mean[i]<0:
        R = 255
        G = 255-int(0.9*255*ratiocof[i]/max(ratiocof))
        B = 255-int(0.9*255*ratiocof[i]/max(ratiocof))
        wid=-1*pcof_mean[i]*10
    else:
        R = 255-int(0.9*255*ratiocof[i]/max(ratiocof))
        G = 255-int(0.9*255*ratiocof[i]/max(ratiocof))
        B = 255
        wid=pcof_mean[i]*10
    color_code = '#{}{}{}'.format(hex(R), hex(G), hex(B))
    color_code = color_code.replace('0x', '')
    colorlis.append(color_code)
    widlis.append(wid)
    rlis.append(R)

In [108]:
rlis

[127,
 0,
 255,
 0,
 0,
 71,
 50,
 108,
 91,
 0,
 132,
 0,
 40,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 66,
 19,
 38,
 45,
 0,
 0,
 82,
 0,
 0,
 0,
 142,
 19,
 0,
 0,
 26,
 51,
 38]

In [18]:
network = Network(
    height="500px",  # デフォルト "500px"
    width="500px",  # デフォルト "500px"
    notebook=True,  # これをTrueにしておくとjupyter上で結果が見れる
    bgcolor='#ffffff',  # 背景色。デフォルト "#ffffff"
    directed=True,  # Trueにすると有向グラフ。デフォルトはFalseで無向グラフ
)

Local cdn resources have problems on chrome/safari when used in jupyter-notebook. 


In [19]:
# add_node でノードを追加
# label は省略可能。省略するとidと同じになる。
network.add_node(n_id=1, label="input", shape="box",x=200,y=0,physics=False)
network.add_node(n_id=2, label="Bacteria", shape="box",color='gray',x=200,y=80,physics=False)
network.add_node(n_id=3, label="Toll-like receptors", shape="box",color='gray',x=200,y=160,physics=False)
network.add_node(n_id=4, label="Effector immune cells", shape="box",color='gray',x=50,y=120,physics=False)
network.add_node(n_id=5, label="Epithelial barrier", shape="box",color='gray',x=350,y=120,physics=False)
network.add_node(n_id=6, label="Monocytes", shape="box",color='gray',x=50,y=250,physics=False)
network.add_node(n_id=7, label="Endothelial damage", shape="box",color='gray',x=350,y=250,physics=False)
network.add_node(n_id=8, label="Osteoclasts", shape="box",color='gray',x=120,y=330,physics=False)
network.add_node(n_id=9, label="Osteoblasts", shape="box",color='gray',x=280,y=330,physics=False)
network.add_node(n_id=10, label="Bone integrity", shape="box",color='gray',x=200,y=430,physics=False)
network.add_node(n_id=11, label="Pdcd1", shape="box",x=40,y=40,physics=False)
network.add_node(n_id=12, label="Il10", shape="box",x=0,y=185,physics=False)
network.add_node(n_id=13, label="Arg1", shape="box",x=50,y=185,physics=False)
network.add_node(n_id=14, label="Ppp1r11", shape="box",x=200,y=230,physics=False)
network.add_node(n_id=15, label="Vegfa", shape="box",x=450,y=200,physics=False)

# add_edge でエッジを追加
network.add_edge(1, 2,width=widlis[0],color=colorlis[0])
#network.add_edge(2, 2,width=widlis[1],color=colorlis[1])
network.add_edge(4, 2,width=widlis[2],color=colorlis[2])
network.add_edge(5, 2,width=widlis[3],color=colorlis[3])
network.add_edge(8, 10,width=widlis[4],color=colorlis[4])
network.add_edge(9, 10,width=widlis[5],color=colorlis[5])
network.add_edge(2, 3,width=widlis[6],color=colorlis[6])
network.add_edge(3, 14,width=widlis[7],color=colorlis[7])
network.add_edge(14, 3,width=widlis[8],color=colorlis[8])
#network.add_edge(14, 14,width=widlis[9],color=colorlis[9])
network.add_edge(3, 5,width=widlis[10],color=colorlis[10])
network.add_edge(3, 4,width=widlis[11],color=colorlis[11])
network.add_edge(4, 11,width=widlis[12],color=colorlis[12])
network.add_edge(11, 4,width=widlis[13],color=colorlis[13])
network.add_edge(6, 13,width=widlis[14],color=colorlis[14])
network.add_edge(13, 4,width=widlis[15],color=colorlis[15])
#network.add_edge(11, 11,width=widlis[16],color=colorlis[16])
#network.add_edge(13, 13,width=widlis[17],color=colorlis[17])
network.add_edge(4, 12,width=widlis[18],color=colorlis[18])
network.add_edge(12, 4,width=widlis[19],color=colorlis[19])
network.add_edge(6, 12,width=widlis[20],color=colorlis[20])
network.add_edge(12, 6,width=widlis[21],color=colorlis[21])
#network.add_edge(12, 12,width=widlis[22],color=colorlis[22])
network.add_edge(3, 7,width=widlis[23],color=colorlis[23])
network.add_edge(7, 15,width=widlis[24],color=colorlis[24])
network.add_edge(15, 7,width=widlis[25],color=colorlis[25])
#network.add_edge(15, 15,width=widlis[26],color=colorlis[26])
network.add_edge(3, 6,width=widlis[27],color=colorlis[27])
network.add_edge(7, 6,width=widlis[28],color=colorlis[28])
network.add_edge(8, 9,width=widlis[29],color=colorlis[29])
#network.add_edge(8, 8,width=widlis[30],color=colorlis[30])
network.add_edge(6, 8,width=widlis[31],color=colorlis[31])
network.add_edge(9, 8,width=widlis[32],color=colorlis[32])

#network.add_edge(2, 4, width=2)  # width で太さを変えられる
#network.add_edge(3, 4, smooth="dynamic")  # smooth を指定することで、エッジを曲線にできる
#network.add_edge(4, 3, smooth="dynamic")  # エッジを曲線にすると双方向のエッジを別の線にできる。(直線だと重なる)

In [20]:
# 指定したファイル名でHTMLを出力。
network.show("pyvis_sample1.html")

In [18]:
ratiocof[23]

2.007323177119957

In [74]:
R = 140
G = 180
B = 250
color_code = '#{}{}{}'.format(hex(R), hex(G), hex(B))
color_code = color_code.replace('0x', '')

In [75]:
color_code

'#8cb4fa'

In [17]:
colorlis[2]

'#ff00'

In [18]:
widlis[2]

0.43637609562830354

In [19]:
int(255*ratiocof[2]/max(ratiocof))

255